# Generated by Django 2.1.1 on 2018-10-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180930_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ユーザー一覧', 'verbose_name_plural': 'ユーザー一覧'},
        ),
    ]
