# Generated by Django 2.1.1 on 2018-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=20)),
                ('contract_period', models.CharField(max_length=20)),
                ('required_skills', models.CharField(max_length=50)),
                ('work_hours', models.CharField(max_length=20)),
                ('time_range', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('contract_type', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
