# Generated by Django 2.1.1 on 2018-09-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20180927_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='interview_times',
            field=models.CharField(default=1, max_length=2, verbose_name='商談回数'),
            preserve_default=False,
        ),
    ]
