# Generated by Django 2.1.1 on 2018-09-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_interview_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='カテゴリ名')),
                ('count', models.IntegerField(verbose_name='offer数')),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_period',
            field=models.IntegerField(verbose_name='契約期間'),
        ),
    ]
