# Generated by Django 2.1.1 on 2018-09-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20180930_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='カテゴリ名'),
        ),
    ]
