# Generated by Django 2.1.1 on 2018-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20180930_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': '案件一覧', 'verbose_name_plural': '案件一覧'},
        ),
        migrations.AlterModelOptions(
            name='offercategory',
            options={'verbose_name': '案件カテゴリ', 'verbose_name_plural': '案件カテゴリ'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_period',
            field=models.CharField(max_length=10, verbose_name='契約期間'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='interview_times',
            field=models.IntegerField(verbose_name='商談回数'),
        ),
    ]
