# Generated by Django 2.1.1 on 2018-10-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20180930_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='OfferCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.OfferCategory', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='offer',
            name='apply_nums',
            field=models.IntegerField(default=0, verbose_name='応募数'),
        ),
        migrations.AddField(
            model_name='offer',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='offer',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
