# Generated by Django 2.1.1 on 2018-10-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_auto_20181005_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='isActive',
            field=models.CharField(choices=[('0', '有効'), ('1', '無効')], default='0', max_length=1, verbose_name='有効'),
        ),
    ]
