# Generated by Django 2.1.1 on 2018-10-11 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0012_offer_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(verbose_name='案件id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '案件收藏',
                'verbose_name_plural': '案件收藏',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='plus_skills',
            field=models.TextField(default=0, max_length=100, verbose_name='尚可スキル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.TextField(max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='required_skills',
            field=models.TextField(max_length=100, verbose_name='必須スキル'),
        ),
    ]
