# Generated by Django 2.1.1 on 2018-10-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_auto_20181011_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='work_phase',
            field=models.CharField(default=0, max_length=10, verbose_name='担当フェーズ'),
            preserve_default=False,
        ),
    ]
