# Generated by Django 2.1.1 on 2018-10-13 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0014_offer_work_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.IntegerField(verbose_name='案件id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '案件応募',
                'verbose_name_plural': '案件応募',
            },
        ),
    ]
