# Generated by Django 2.1.1 on 2018-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_userapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
