# Generated by Django 2.1.1 on 2018-10-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_auto_20181017_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='create_by',
            field=models.CharField(max_length=50, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='last_modified_by',
            field=models.CharField(max_length=50, verbose_name='最終更新者'),
        ),
    ]
