# Generated by Django 2.1.1 on 2018-10-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_auto_20181021_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='OfferCategory',
            new_name='offerCategory',
        ),
    ]
